tasks:
  - init: |
      docker run --name  -mysqle MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=mydb -p 3306:3306 -d mysql:latest
      python -c "from app.database import init_db; init_db()"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload